version: '3'

services:
  quetre:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "doc:3000"
    environment:
      - "NODE_ENV=production"
      - "PORT=3000"
      - "CACHE_PERIOD=1h"
      - "REDIS_URL=redis:6379" # optional
      - "REDIS_TTL=3600"
  redis:
   image: docker.io/redis:alpine
   container_name: redis
   restart: unless-stopped