services:

  quetre:
    container_name: quetre
    image: ghcr.io/zyachel/quetre:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000" # Replace with "3000:3000" if you don't use a reverse proxy
    environment:
      - "NODE_ENV=production"
      - "PORT=3000"
